services:
  rest:
    init: true
    build:
      context: .
      dockerfile: ./RestAPI/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - dal

  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./FrontEnd:/usr/share/nginx/html
    command: ["nginx", '-g', 'daemon off;']

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    command:
        - postgres
        - -c
        - listen_addresses=*
      
  dal:
    image: dal_image
    build:
      context: .
      dockerfile: ./DAL/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      
# manage the volume which is named db
volumes:
  db: