services:
  web:
    init: true
    build: ./RestAPI
    ports:
      - "8081:8081"
    #uncomment for windows
    #networks:
    # - web

    #uncomment for linux
    network_mode: host
networks:
  web:
