services:
  rest:
    init: true
    build:
      context: .
      dockerfile: ./RestAPI/Dockerfile
    ports:
      - "8081:8081"

  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./FrontEnd:/usr/share/nginx/html
    command: ["nginx", '-g', 'daemon off;']

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    command:
        - postgres
        - -c
        - listen_addresses=*

  adminer:
    image: adminer
    ports:
      - "9091:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password
      ports:
        - "5672:5672"
        - "9093:15672"

# manage the volume which is named db
volumes:
  db: