name: .NET 8.0 Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the projects
      run: dotnet build --configuration Release

    - name: Run Unit Tests - DALTests
      run: dotnet test ./UnitTests/DALTests/DALTests.csproj --configuration Release --no-build --verbosity normal

    - name: Run Unit Tests - RestAPITests
      run: dotnet test ./UnitTests/RestAPITests/RestAPITests.csproj --configuration Release --no-build --verbosity normal

    - name: Publish Test Results
      if: always()
      run: |
        mkdir -p $GITHUB_WORKSPACE/test-results
        dotnet test ./UnitTests/DALTests/DALTests.csproj --configuration Release --no-build --logger "trx;LogFileName=test-RESULTS-DALTests.trx"
        dotnet test ./UnitTests/RestAPITests/RestAPITests.csproj --configuration Release --no-build --logger "trx;LogFileName=test-RESULTS-RestAPITests.trx"
        mv *.trx $GITHUB_WORKSPACE/test-results/
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: $GITHUB_WORKSPACE/test-results

